# Generated by Django 4.2.5 on 2023-11-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='profile.png', upload_to='tovar/%Y/%m/%d'),
        ),
    ]
